export const musicList = [
    {
        id: 0,
        artist: 'Josean Log',
        songName: 'Beso',
        description: 'Beso Josean Log',
        filePath: '../music/Josean_Log_Beso.mp3',
        duration: 211,
        favorite: false,
        popular: true,
    },
    {
        id: 1,
        artist: 'Josean Log',
        songName: 'Chachacha',
        description: 'Chachacha Josean Log',
        filePath: '../music/Josean_Log_Chachacha.mp3',
        duration: 216,
        favorite: false,
        popular: true,
    },
    {
        id: 2,
        artist: 'Josean Log',
        songName: 'Doma',
        description: 'Doma Josean Log',
        filePath: '../music/Josean_Log_Doma.mp3',
        imagePath: 'images/doma.jpg',
        duration: 188,
        favorite: false,
        popular: true,
    },
    {
        id: 3,
        artist: 'Josean Log',
        songName: 'La Luna',
        description: 'La Luna Josean Log',
        filePath: '../music/Josean_Log_La_Luna.mp3',
        duration: 243,
        favorite: false,
        popular: true,
    },
    {
        id: 4,
        artist: 'Josean Log',
        songName: 'Tierra',
        description: 'Tierra Josean Log',
        filePath: '../music/Josean_Log_Tierra.mp3',
        duration: 182,
        favorite: false,
        popular: false,
    },
    {
        id: 5,
        artist: 'John Deley and the 41 Players',
        songName: 'Dewey, Cheedham, and Howe (Sting)',
        description: 'Dewey, Cheedham, and Howe (Sting) John Deley and the 41 Players',
        filePath: '../music/John_Deley.mp3',
        duration: 7,
        favorite: false,
        popular: false,
   },
    {
        id: 6,
        artist: 'MK2',
        songName: 'Hero Theme (Sting)',
        description: 'Hero Theme (Sting) MK2',
        filePath: '../music/Hero_Theme.mp3',
        duration: 10,
        favorite: false,
        popular: false,
   },
    {
        id: 7,
        artist: 'Oliver Tree',
        songName: 'Miss You Music Video',
        description: 'Oliver Tree  Robin Schulz  Miss You Music Video',
        filePath: '../music/Oliver_Tree_Robin_Schulz _Miss_You_Music_Video.mp3',
        duration: 168,
        favorite: false,
        popular: true,
   },
    {
        id: 8,
        artist: 'Luminati Suns',
        songName: 'My Stupid Heart - Walk off the Earth',
        description: 'My Stupid Heart - Walk off the Earth (Ft. Luminati Suns) Official Video',
        filePath: '../music/My_Stupid_Heart_Walk _off_the_Earth_(Ft. Luminati Suns)_Official_Video.mp3',
        duration: 172,
        favorite: false,
        popular: true,
   },
    {
        id: 9,
        artist: 'sapientdream',
        songName: 'sapientdream - Pastlives',
        description: 'sapientdream - Pastlives',
        filePath: '../music/sapientdream_Pastlives.mp3',
        duration: 153,
        favorite: false,
        popular: false,
   },
    {
        id: 10,
        artist: 'Powfu',
        songName: 'Powfu - death bed (coffee for your head) (Official Video) ft. beabadoobee',
        description: 'Powfu - death bed (coffee for your head) (Official Video) ft. beabadoobee',
        filePath: '../music/Powfu_death_bed_(coffee for your head)_(Official Video)_ft._beabadoobee.mp3',
        duration: 153,
        favorite: false,
        popular: false,
   }
];